[package]
name = "my-jira"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reedline = "0.18.0"
serde = "1.0.160"
serde_json = "1.0.96"
